site_name: hashin_shtrikman_mp
site_description: Documentation for the hashin-shtrikman-mp package
copyright: Built by Carla Becker, Hrushikesh Sahasrabuddhe, and Max C. Gallant

watch:
  - src/hashin_shtrikman_mp

nav:
  - Home: index.md
  - Examples:
    - Getting Started: getting_started.md
    - 3-phase Composite Example: ./examples/example_n=3.ipynb
    - Example Phase Diagram Visualizations: ./examples/example_plotting.ipynb
  - Documentation:
    - Genetic Algorithm:
      - GeneticAlgorithmParams: ./reference/core/genetic_algorithm/genetic_algorithm_parameters.md
      - GeneticAlgorithmResult: ./reference/core/genetic_algorithm/genetic_algorithm_result.md
      - GeneticAlgorithm: ./reference/core/genetic_algorithm/genetic_algorithm.md
      - Member: ./reference/core/genetic_algorithm/member.md
      - OptimizationParams: ./reference/core/genetic_algorithm/optimization_params.md
      - Population: ./reference/core/genetic_algorithm/population.md
    - User Input:
      - Aggregate: ./reference/core/user_input/aggregate.md
    - Visualization:
      - CompositePropertyPlotter: ./reference/core/visualization/composite_property_plotter.md
      - OptimizationResultVisualizer: ./reference/core/visualization/optimization_result_visualizer.md
    - MatchFinder: ./reference/core/match_finder.md

repo_url: https://github.com/carlacupcake/hashin_shtrikman_mp/
repo_name: Github

theme:
  name: mkdocs
  icon:
    logo: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
  color_mode: light
  user_color_mode_toggle: true
  nav_style: primary
  hljs_languages:
    - yaml
    - python
  locale: en

plugins:
  - search
  - section-index
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            new_path_syntax: yes

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
