site_name: hashin_shtrikman_mp
site_description: Documentation for the hashin-shtrikman-mp package
copyright: Built by Carla Becker, Hrushikesh Sahasrabuddhe, and Max C. Gallant

watch:
  - ../src/hashin_shtrikman_mp

nav:
  - Home:
    - Welcome: index.md
    - Getting Started: ./guides/getting_started.ipynb
    - Reference: reference/core/optimizer.md
    - Guides: ./guides/index.md
  - Guides:
    - Getting Started: ./guides/getting_started.ipynb
  - Reference:
    - Optimizer: ./reference/core/optimizer.md
    - GAParams: ./reference/core/genetic_algo.md
    - Member: ./reference/core/member.md
    - Population: ./reference/core/population.md
    - UserInput: ./reference/core/user_input.md
    - Visualizer: ./reference/core/visualizer.md
    - MatchFinder: ./reference/core/match_finder.md

repo_url: https://github.com/carlacupcake/hashin_shtrikman_mp/
repo_name: Github

theme:
  name: mkdocs
  icon:
    logo: img/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
  color_mode: light
  user_color_mode_toggle: true
  nav_style: primary
  hljs_languages:
    - yaml
    - python
  locale: en
